#!/bin/bash
app=movim

# Retrieve arguments
domain=$1
path=$2
admin=$3


# Check if admin exists
sudo yunohost user list --json | grep -q "\"username\": \"$admin\""
if [[ ! $? -eq 0 ]]; then
	echo "Wrong admin"
	exit 1
fi

# Save app settings
sudo yunohost app setting $app admin -v "$admin"
sudo yunohost app setting $app is_public -v "$is_public"

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Install PHP dependency
sudo apt-get update
sudo apt-get install -y php5-cli

# Generate random password
db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p')

# Use 'movim' as database name and user
db_user=movim

# Initialize database and store mysql password for upgrade
sudo yunohost app initdb $db_user -p $db_pwd
sudo yunohost app setting movim mysqlpwd -v $db_pwd

# Copy source files
final_path=/var/www/$app
sudo mkdir -p $final_path

sudo mkdir /tmp/movim
sudo wget https://launchpad.net/movim/0.8/0.8.1/+download/movim-0.8.1.zip --output-document=/tmp/movim/movim.zip

sudo unzip -a /tmp/movim/movim.zip -d /tmp/movim

sudo cp -a /tmp/movim/movim*/* $final_path

sudo rm -rf /tmp/movim

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
sudo cp ../conf/db.inc.php $final_path/config/db.inc.php

# Replace db password in config
sudo sed -i "s/passwordToChange/$db_pwd/" $final_path/config/db.inc.php

sudo mkdir $final_path/users $final_path/log $final_path/cache

# Set permissions to movim directory
sudo chown -R www-data: $final_path

sudo find $final_path -type f | xargs sudo chmod 644
sudo find $final_path -type d | xargs sudo chmod 755

su - www-data -c 'php5 $final_path/mud.php getloc'
su - www-data -c 'php5 $final_path/mud.php comploc'
su - www-data -c 'php5 $final_path/mud.php comptz'
su - www-data -c 'php5 $final_path/mud.php db'

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf
